### ISSUE TITLE
Composer update problem!

### ISSUE THREAD

**Issue by shamanis** [zfcampus/zf-oauth2#110] opened 2015-07-20 08:26 UTC
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - zfcampus/zf-oauth2 1.3.0 requires bshaffer/oauth2-server-php ~1.7 -> no matching package found.
    - zfcampus/zf-oauth2 1.2.0 requires bshaffer/oauth2-server-php ~1.7 -> no matching package found.
    - zfcampus/zf-oauth2 1.1.3 requires bshaffer/oauth2-server-php ~1.3 -> no matching package found.
    - zfcampus/zf-oauth2 1.1.2 requires bshaffer/oauth2-server-php ~1.3 -> no matching package found.
    - zfcampus/zf-oauth2 1.1.1 requires bshaffer/oauth2-server-php ~1.3 -> no matching package found.
    - zfcampus/zf-oauth2 1.1.0 requires bshaffer/oauth2-server-php ~1.3 -> no matching package found.
    - zfcampus/zf-oauth2 1.0.3 requires bshaffer/oauth2-server-php ~1.3 -> no matching package found.
    - zfcampus/zf-oauth2 1.0.2 requires bshaffer/oauth2-server-php ~1.3 -> no matching package found.
    - zfcampus/zf-oauth2 1.0.1 requires bshaffer/oauth2-server-php ~1.3 -> no matching package found.
    - zfcampus/zf-oauth2 1.0.0 requires bshaffer/oauth2-server-php ~1.3 -> no matching package found.
    - zfcampus/zf-oauth2 1.1.x-dev requires bshaffer/oauth2-server-php ~1.3 -> no matching package found.

**Comment by ezimuel** [comment] 2015-07-20 16:31
@shamanis I just tried with tag 1.2.0 (PHP >= 5.3.23) and 1.3.0 (PHP >= 5.5) and composer update works fine. Which version of zf-oauth2 are you using? It sounds like a composer issue, maybe a temporary one.

**Comment by shamanis** [comment] 2015-07-21 10:40
@ezimuel dev-master

**Comment by ezimuel** [comment] 2015-07-21 12:01
@shamanis I checked again, even with dev-master, everything work fine. I'm closing the issue because I cannot reproduce it. Thanks!

**Closed by ezimuel** 2015-07-21 12:01 UTC
